FROM python:3.11-slim

WORKDIR /app

COPY requirements-base.txt .
RUN pip install --no-cache-dir -r requirements-base.txt

COPY requirements-extra.txt .
RUN pip install --no-cache-dir -r requirements-extra.txt

COPY serve.py .

CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "5000"]
